### ISSUE TITLE
Selecionar um caso de uso para ser implementado na SPRINT 1. Escrever os fluxos alternativos do caso de uso selecionado.

### ISSUE THREAD

**Issue by tmsasaki** [brn-andrade/ppads-projeto-05j-2018s2#2]

**Comment by renatharolim** [comment]
[Use Cases.pdf](https://github.com/brn-andrade/ppads-projeto-05j-2018s2/files/2384812/Use.Cases.pdf)

**Comment by tmsasaki** [comment]
No arquivo casos-de-uso.md, escrever os fluxos alternativos de "Inserir produtos" e "Inserir restaurantes".

**Comment by tmsasaki** [comment]
Os fluxos alternativos também devem ser descritos na forma de passos (veja o comentário em #1).

**Comment by renatharolim** [comment]
[A2.pdf](https://github.com/brn-andrade/ppads-projeto-05j-2018s2/files/2520927/A2.pdf)
Atividade 2 - Caso de uso da Sprint 1com fluxos alternativos
